<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class RawQueryTest extends TestCase
{   
    protected function setUp(): void
    {
        parent::setUp(); //TODO; Change the autogenerated stub
        DB::delete('delete from categories');
    }
    /**
     * A basic feature test example.
     */
    public function testCrud()
    {
        DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
            "GADGET", "Gadget", "Gadget Category", "2020-10-10 10:10:10"
        ]);

        $result = DB::select('select * from categories where id = ?', ['GADGET']);

        self::assertCount(1, $results);
        self::assertEquals('GADGET', $result[0]->id);
        self::assertEquals('Gadget', $result[0]->name);
        self::assertEquals('Gadget Category', $result[0]->description);
        self::assertEquals('2020-10-10 10:10:10', $result[0]->created_at);
    }
}
